version: '3.9'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - MYSQL_HOST=mysqldb
    ports:
      - 8080:8080
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

volumes:
  db:
